<a href="https://colab.research.google.com/github/JanhviSharma1/Practice-Scikit-/blob/main/D1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1, 2, 3, 4, 5, 6])
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr[1:3])
newarr= arr.astype('f')
print(newarr)
x=arr.copy()
y=arr.view()
arr[0]=0
print(x)
print(y)
print(x.base)
print(y.base)
print(newarr.shape)
print(arr.reshape(2,3))
print(arr.reshape(-1)) #flattening an arr
for x in np.nditer(arr):
    print(x)
for idx, x in np.ndenumerate(arr): #iterating along with index
    print(idx, x)

[1 2 3 4 5 6]
int64
<class 'numpy.ndarray'>
1
[2 3]
[1. 2. 3. 4. 5. 6.]
[1 2 3 4 5 6]
[0 2 3 4 5 6]
None
[0 2 3 4 5 6]
(6,)
[[0 2 3]
 [4 5 6]]
[0 2 3 4 5 6]
0
2
3
4
5
6
(0,) 0
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6


**Concatenation (along with axis)**

•	array1, array2, ... → Arrays to concatenate (must have the same shape except along the axis of concatenation).

•	axis → The dimension along which concatenation happens:

•	axis=0 → Concatenates along rows (vertically)

•	axis=1 → Concatenates along columns (horizontally)

•	axis=None → Flattens the arrays before concatenation

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr) # [[1 2 5 6] [3 4 7 8]]
arr = np.concatenate((arr1, arr2), axis=0)
print(arr) # [[1 2] [3 4] [5 6] [7 8]]
arr = np.concatenate((arr1, arr2), axis=None)
print(arr) # [1 2 3 4 5 6 7 8]

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[1 2 3 4 5 6 7 8]


**Stack**

•	array1, array2, ... → Arrays to be stacked (must have the same shape).

•	axis → The dimension where a new axis is inserted:

axis=0 → New dimension added as the first axis.

axis=1 → New dimension added as the second axis.

axis=2, axis=-1, etc., can be used for higher dimensions.

•	np.vstack((a, b)) → Equivalent to np.stack((a, b), axis=0), but only for vertical stacking.

•	np.hstack((a, b)) → Equivalent to np.concatenate((a, b), axis=1), but only for horizontal stacking.

•	np.dstack((a, b)) → Equivalent to np.stack((a, b), axis=2) (stacks along height, which is same as depth

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr) #[1 2 3 4 5 6]
arr = np.vstack((arr1, arr2))
print(arr)#[[1 2 3][4 5 6]]
arr = np.dstack((arr1, arr2))
print(arr) #[[[1 4][2 5][3 6]]]

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]
